### ISSUE TITLE
Backdoor Problem

### ISSUE THREAD

**Issue by TWIST-X7** [3ct0s/disctopia-c2#19]
When I executed The BACKDOOR to test if its working its showed me an error That said "Failed to execute script {Name Of The Backdoor}"

![error](https://user-images.githubusercontent.com/92231530/153504766-1d06240c-0df2-4821-8257-b7693d25c629.png)

**Comment by 3ct0s** [comment]
There is something wrong with the code. You will need to create a backdoor with debug mode to get the error displayed. So when you are in the builder you will need to run build -d and this will enable debug mode and show a window when you run the backdoor. In that window you should see the error. Share that here.

**Comment by ruskichris** [comment]
Apologies for the saturation but here is what I get and I wouldnt doubt he gets it either, I did pass a proper bot token though for this. https://i.imgur.com/RQW4YUE.png

**Comment by TWIST-X7** [comment]
ok id did evrithyng you said build -d and it showed me this error:
Traceback (most recent call last):
  File "None.py", line 137, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\TWISTX7\\.config\\ID'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "None.py", line 150, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\TWISTX7\\.config\\ID'
[4316] Failed to execute script None

**Comment by 3ct0s** [comment]
@ruskichris I suggest you generate a new from the bot page in discord.com/developers and input that one instead.

@TWIST-X7 hmm, this is a weird error because if the bot does not find the ID file it generates it on its own. Can you manually go to the specified directory and see if the file is missing? If it is can you manually create one call it ID (with no extension) and add any 4 digit number you want? Then try to run the backdoor and let us know how it goes.

**Comment by TWIST-X7** [comment]
you mend i create a file named ID5436 in C:\Users\TWISTX7\.config directory and then run the backdor

**Comment by Swetsss123** [comment]
ls dist does not work for me
