### ISSUE TITLE
Cant run the RAT

### ISSUE THREAD

**Issue by Scratch-490** [3ct0s/disctopia-c2#22]
When I run the program it says 
**Failed to execute script Backdoor**
![image](https://user-images.githubusercontent.com/53001266/155275109-5ff2231d-73cb-4072-880c-a59d494ad037.png)

**Comment by 3ct0s** [comment]
It appears there was an error with the script. You will need to create a new backdoor using the debug mode. So in the builder, once you get to the point where you type "build" to generate the backdoor type "build -d" instead to enable the debug mode. This will enable a window on the backdoor and it should display your error. Once you have that error please send it here so that we can review it.

**Comment by Scratch-490** [comment]
I did it again as you said, this time when it seems to run fine but when executed the RAT opens up a cmd windows, which I think is the debug menu, dk y but it works now
