### ISSUE TITLE
safe to do on my computer our better to host it on a cloud vm?

### ISSUE THREAD

**Issue by ExdmundZ** [3ct0s/disctopia-c2#43]
safe to do on my computer our better to host it on a cloud vm?

**Comment by dennixone** [comment]
Guy c2 is in Discord you dont need to host anything.

**Comment by SinThroughCode** [comment]
it's probably best to host the bot on a VPS so you can have it running 24/7 instead of keeping your pc on 24/7 plus it's alot faster and doesn't use up your pc resources to run the bot. But if you're about safety there isn't really much that can harm you by this setup. Worst case is someone finds out what your webhook link is then they spam it with random crap and you just gotta make a new webhook and you're good. Other than that, I don't really think there is anything that can screw you over. However if you are going to run this locally on your own connection i suggest running it on a vpn as well so people can't ddoss you if they get the ip from the bot
