### ISSUE TITLE
amazing.. good job

### ISSUE THREAD

**Issue by rogldicksn** [3ct0s/disctopia-c2#8]
this is awesome..

can you add more commands like install and unistall apps

list directory to view files etc ?

**Comment by 3ct0s** [comment]
Hi There,
You download and install apps using the !cmd command or upload an application installer to the Agent using the !upload command.

Also, to list the directories and files you can use the !cmd command.

**Comment by rogldicksn** [comment]
![image](https://user-images.githubusercontent.com/76434629/150001791-51c042fc-1282-4736-b925-de1506ad19e2.png)


I get this error when i run the !credentials command on some targets 

also i used the !upload command to upload .

could you give an example use for the !cmd  to install an app on targets machines and to list directories on target machine

**Comment by 3ct0s** [comment]
The agent needs to have Chrome installed in order for the command to work. In the example, It looks like it is not installed. That is why it cannot find the path.

Ok so since you don't have access to GUI (Graphical User Interface) and you only have access to the command line, you will need to find installers that can be executed silently (to not raise awareness) from the command line.

To list the directories you can run the command **!cmd ID dir PATH** 
You need to replace ID with the Agent ID and the PATH with the actual path on the system that you want to view.

**Comment by rogldicksn** [comment]
![image](https://user-images.githubusercontent.com/76434629/150005731-589c66f7-a6c2-4160-a234-1f91bed2fe04.png)


i get this when i run the !cmd ID dir PATH command 

also could you suggest any GUI to me

thanks

**Comment by 3ct0s** [comment]
Can you please show me the complete command that you executed and got this result?
And also as I said, you cannot have access to the GUI through this backdoor, you will need to install applications with the command line through the !cmd Disctopia command.

**Comment by 3ct0s** [comment]
I think the problem here is that you have entered USERNAME as the user's username. This will only be replaced in the !download command, not in the !cmd command. Please try again with the actually Username, it should work.

**Comment by rogldicksn** [comment]
@3ct0s 
**Awesome**.. it works perfectly.

**Great Project**.. looking forward to more features added in the near future.

**Comment by 3ct0s** [comment]
Thank you, glad you got it working ;)
