### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by hamrainbow** [3ct0s/disctopia-c2#84]
wine: failed to open "/root/.wine/drive_c/users/root/AppData/Local/Programs/Python/Python38-32/Scripts/pyinstaller.exe": c0000135

**Comment by JohnG1985** [comment]
This error message indicates that the program you are trying to run, pyinstaller.exe, is not installed or is not in the correct location. The error message states that the program is not in the directory /root/.wine/drive_c/users/root/AppData/Local/Programs/Python/Python38-32/Scripts/, which is where it is expected to be.

One possible reason for this error is that the program was not installed correctly. To fix this, you can try reinstalling the program and making sure it is installed in the correct location. You can also check the location where the program is installed and make sure that it matches the location specified in the error message.

If you continue to have issues, you may need to troubleshoot further to determine the root cause of the problem. This may involve checking for any additional errors or messages that may provide more information about the issue. It may also be helpful to check for any updates or patches for the program that may address the issue.

**Comment by 3ct0s** [comment]
Checkout the latest version of Disctipia. I just pushed a commit that fixies a dependency error. I installed it on a fresh Kali VM and successfully built a backdoor.

**Comment by CyberPro010** [comment]
> wine: failed to open "/root/.wine/drive_c/users/root/AppData/Local/Programs/Python/Python38-32/Scripts/pyinstaller.exe": c0000135

still don't work on my kali
